#if defined __autogenerated_methodmap_{{classname}}_included
	#endinput
#endif

#define __autogenerated_methodmap_{{classname}}_included

{{#decl_variables}}
any {{var}};
{{/decl_variables}}

/**
 * This is an autogenerated methodmap to access the properties of a(n) {{classname}} instance.
 */
methodmap {{classname}}{{#inherits}} < {{inherits}}{{/inherits}} {
	/**
	 * Returns the address casted to a {{classname}} methodmap instance.
	 */
	public static {{classname}} FromAddress(Address pInstance) {
		return view_as<{{classname}}>(pInstance);
	}
{{#methods_file}}
	
	#include "{{methods_file}}"
{{/methods_file}}
	
	property Address Address {
		public get() {
			return view_as<Address>(this);
		}
	}
{{#properties}}
	
	property {{type}} {{name}} {
		public get() {
{{^inline}}
			return view_as<{{type}}>(LoadFromAddress(this.Address + view_as<Address>({{offset}}), {{size}}));
{{/inline}}
{{#inline}}
			return view_as<{{type}}>(this.Address + view_as<Address>({{offset}}));
{{/inline}}
		}
{{#writable}}{{^inline}}
		public set({{type}} value) {
			StoreToAddress(this.Address + view_as<Address>({{offset}}), view_as<any>(value), {{size}});
		}
{{/inline}}{{/writable}}
	}
{{/properties}}
{{#size}}
	
	public static int GetClassSize() {
		return {{size}};
	}
{{/size}}
}
